---
- name: Changed motd
  hosts: yandex_vm
  remote_user: tata
  become: yes
  
  tasks:
    - name: Disable  MOTD scripts
      shell: chmod -x /etc/update-motd.d/*
    
    - name: Set motd 
      template:
        src: motd.j2
        dest: /etc/motd
        

   
  
